/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedUpgradeRouteImport } from './routes/_authed/upgrade'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as IPublicIdRouteImport } from './routes/i.$publicId'
import { Route as AuthedInvoicesIdRouteImport } from './routes/_authed/invoices.$id'
import { Route as AuthedInvoicesNewRouteImport } from './routes/_authed/invoices.new'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpgradeRoute = AuthedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IPublicIdRoute = IPublicIdRouteImport.update({
  id: '/i/$publicId',
  path: '/i/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInvoicesIdRoute = AuthedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesNewRoute = AuthedInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/upgrade': typeof AuthedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/upgrade': typeof AuthedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/upgrade': typeof AuthedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/i/$publicId': typeof IPublicIdRoute
  '/_authed/invoices/$id': typeof AuthedInvoicesIdRoute
  '/_authed/invoices/new': typeof AuthedInvoicesNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/update-password'
    | '/i/$publicId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/update-password'
    | '/i/$publicId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authed/dashboard'
    | '/_authed/upgrade'
    | '/auth/callback'
    | '/auth/update-password'
    | '/i/$publicId'
    | '/_authed/invoices/$id'
    | '/_authed/invoices/new'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  IPublicIdRoute: typeof IPublicIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/upgrade': {
      id: '/_authed/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthedUpgradeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$publicId': {
      id: '/i/$publicId'
      path: '/i/$publicId'
      fullPath: '/i/$publicId'
      preLoaderRoute: typeof IPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/invoices/$id': {
      id: '/_authed/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthedInvoicesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices/new': {
      id: '/_authed/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthedInvoicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedUpgradeRoute: typeof AuthedUpgradeRoute
  AuthedInvoicesIdRoute: typeof AuthedInvoicesIdRoute
  AuthedInvoicesNewRoute: typeof AuthedInvoicesNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedUpgradeRoute: AuthedUpgradeRoute,
  AuthedInvoicesIdRoute: AuthedInvoicesIdRoute,
  AuthedInvoicesNewRoute: AuthedInvoicesNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  IPublicIdRoute: IPublicIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
